### ISSUE TITLE
Excel file not generated

### ISSUE THREAD

**Issue by shails** [joashp/simple-php-coupon-code-generator#1]
Hey Josh , 

The coupon generation is working fine but they dont get exported to the excel file .

**Comment by joashp** [comment]
Hi @shails , 
I add not added a UI export functionality. Only a PHP function to export.
Just made a new change and added functionality to export to excel in Frontend UI as well.
 More details in the commit https://github.com/joashp/simple-php-coupon-code-generator/commit/67890eee51a605ae1360667e28b91e1ddb30a243
