### ISSUE TITLE
Custom values not working

### ISSUE THREAD

**Issue by ActionCodeX** [joashp/simple-php-coupon-code-generator#6]
Hi,

None of the custom values (other than Number of coupons) appear to be working. I also just noticed the length is always 8 characters, where the default value in the field is 6 characters.

Wanted to pass this along. I'm new to php and this project has been valuable for my learning.

Best,

**Comment by chupzzz** [comment]
Confirm! None of parameters are working.

**Comment by chupzzz** [comment]
It's simple mistake: in index.php there is a wrong example. Change line 14 in index.php to:

`$coupons = coupon::generate_coupons($no_of_coupons, ['length' => $length, 'prefix' => $prefix, 'suffix' => $suffix, 'numbers' => $numbers, 'letters' => $letters, 'symbols' => $symbols, 'random_register' => $random_register, 'mask' => $mask]);`

**Comment by ActionCodeX** [comment]
Got it! Thank you.
